Wrapped Funnel - AnalysisButton - onClick Debug (#372)
* Wrapped Funnel - AnalysisButton - onClick Debug

   - actual: AnalysisButton - onClick is throwing an error
   - required: AnalysisButton - onClick should trigger socket connection to the Recoup API to start the initial tavily agent

     - reference: components/Funnels/AnalysisButton.tsx
     - ERROR

     ```
     Unhandled Runtime Error
     TypeError: Cannot read properties of undefined (reading 'replaceAll')

     Source
     hooks/useAgentSocket.tsx (62:40) @ replaceAll

       60 |       funnels.map((funnel) => {
       61 |         socketIo.emit(`${funnel.toUpperCase()}_ANALYSIS`, socketId, {
     > 62 |           handle: handles[`${funnel}`].replaceAll("@", "") || "",
         |                                        ^
       63 |           pilot_id: chatId,
       64 |           account_id: userData?.account_id,
       65 |           address,
     ```

* remove dev comments.